# Generated by Django 2.2.1 on 2019-05-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('algorithme', models.IntegerField()),
                ('database', models.IntegerField()),
                ('computer_network', models.IntegerField()),
                ('computer_structure', models.IntegerField()),
                ('data_structure', models.IntegerField()),
                ('operation_system', models.IntegerField()),
                ('software_engineering', models.IntegerField()),
            ],
        ),
    ]
