# Generated by Django 2.2.1 on 2019-05-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190517_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pr_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
