# Generated by Django 2.2.1 on 2019-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_auto_20190517_1446'),
        ('quiz', '0002_auto_20190516_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=None, to='register.User')),
                ('pr_id', models.ForeignKey(on_delete=None, to='quiz.QuizModel')),
            ],
        ),
    ]
